### ISSUE TITLE
Feature Request: Rotate Vox file / delete blocks where all sides are air

### ISSUE THREAD

**Issue by superfrantv** [Zarbuz/FileToVox#10]
Hello,

the title says all. I wish you could make two new Commands (like --e).
1. Rotate the object before export to vox file.
2. Delete every single block that is not connected to any other block.

Thank you for this great Progamm!

**Comment by superfrantv** [comment]
I see you changed the label.
Please inform me here if this features are available, its important for my work.
With that features i can speed up my development for a very big features game.

Thanks so much for this great Progamm!

**Comment by Zarbuz** [comment]
I don't see any interest for the rotate object feature, you can already do this in MagicaVoxel, but the deleting every single block that is not connected to any other block is interesting.

**Comment by superfrantv** [comment]
Iam need the rotate Feature for my command line Programm, because magica voxel has no command line Mode and its very Important to automate this, also if i convert a. Ply File to vox it is Wrong rotated when iam Import them in Unity, Blender or isovoxel, please add this little Feature too.

**Comment by Zarbuz** [comment]
Sorry won't be added.

**Comment by superfrantv** [comment]
Thats sad but the other Feature is also very usefull.

**Comment by Zarbuz** [comment]
New command will be available in the next version (--fix-lonely)

**Comment by Zarbuz** [comment]
New command will be available in the next version (--fix-lonely)
