### ISSUE TITLE
Wrong Rotation

### ISSUE THREAD

**Issue by superfrantv** [Zarbuz/FileToVox#19]
Hello,

sry but iam must say it. 
When iam convert any .ply / .png or .obj with FileToVox to a vox file, 
then open it in MagicaVoxel or IsoVoxel and export them as Iso Sprite, 
in both programs is the rotation wrong.

sry for my bad english.

Greetings from germany.

and a little bug, since the new --fix-lonely is here, the empty chunks still exists.

**Comment by Zarbuz** [comment]
Hello, 

Can you provide some screenshots or the vox itself ? It’s hard to see the problem with those informations.

**Comment by superfrantv** [comment]
Yes iam upload the vox. 
When I open the file in MagicaVoxel, the rotation looks good, but if you click on Export as Iso, you can quickly see that the rotation is not correct.

https://www.file-upload.net/download-14004995/Test_000020_SAMPLED_POINTS.vox.html

**Comment by superfrantv** [comment]
And you see the little points on the edge? thats only 1 blocks as marker for my 3d models canvas size but they --fix-lonely is not working?

**Comment by Zarbuz** [comment]
I've to say I've no idea what's going on here .. I have never used the ISO export function :/ 
For the --fix-lonely I found the problem
