### ISSUE TITLE
How to install it on Mac

### ISSUE THREAD

**Issue by BrandoZhang** [Zarbuz/FileToVox#20]
Hi,
Thanks for your great work! I wanna know how to install FileToVox on macOS. 
After unzipping the lastest release I got an `.exe` file which cannot directly be executed in macOS's terminal. Any solution?

**Comment by Zarbuz** [comment]
You have the equivalent of  the Windows version in the same .zip
![image](https://user-images.githubusercontent.com/4965714/80490879-483d5200-8962-11ea-9839-21050924d9ed.png)

The behaviour is quite the same, just remove the ".exe" when you launch your command ;)

**Comment by BrandoZhang** [comment]
Thanks! I got it! 👍
BTW, the link to download `.Net Core Runtime` for macOS should be: https://dotnet.microsoft.com/download/dotnet-core/3.1, go for `installers` in `.NET Core Runtime 3.1.3`.

There is no macOS installer in the link provided in the README file.

**Comment by enzyme69** [comment]
@BrandoZhang Do you have MacOS compiled version of FileToVox? I kind of need in desperate to try it.

**Comment by enzyme69** [comment]
UPDATE:
Somewhat after installing dotnet, I can run:
dotnet FileToVox.dll -i /Users/jimmygunawan/Desktop/heightmap.png -scale 20 -o heightmap
