### ISSUE TITLE
A fatal error occurred. The required library hostfxr.dll could not be found.

### ISSUE THREAD

**Issue by dangerstudios** [Zarbuz/FileToVox#24]
If this is a self-contained application, that library should exist in [\\path\to\MagicaVoxel\FileToVox-v1.10\].
If this is a framework-dependent application, install the runtime in the global location [C:\Program Files\dotnet] or use the DOTNET_ROOT environment variable to specify the runtime location or register the runtime location in [HKLM\SOFTWARE\dotnet\Setup\InstalledVersions\x64\InstallLocation].

**Comment by Zarbuz** [comment]
You need to install the .NET Core Runtime Library : https://dotnet.microsoft.com/download/dotnet-core/current/runtime
