### ISSUE TITLE
Scale bei Schematic gehz nicht

### ISSUE THREAD

**Issue by superfrantv** [Zarbuz/FileToVox#25]
Gruß,
wenn ich ein mehrteiliges Schematic convertiere und die Scale Option 2 nehme, dann fehlt die Hälfte.

**Comment by Zarbuz** [comment]
Please write issue in english only.

**Comment by superfrantv** [comment]
Okay, if i convert a schematic file and take the scale command with a argument of 2, the most of my minecraft schematic is wrong, its dont use the chunk size for scale.

**Comment by Zarbuz** [comment]
Ok . Can you provide your schematic which failed for debugging ?

**Comment by superfrantv** [comment]
Hey Zarbuz,
its with all schematics i used, take any schematic from MineWays like a complete Island, make scale of 2 in command in filetovox and its seems not correct. if i change the chunk size it doents change anything

**Comment by superfrantv** [comment]
Its need to calculate the chunk size, if i take a 256 x 256 x 128 (chunksize 256) Schematic and set a scale of 2, it should be 512 x 512 x256 but with also chunksize 256

**Comment by superfrantv** [comment]
Heres a sample schematic:
https://www.file-upload.net/download-14478582/Novigrad2.schematic.html

Export it with only: FileToVox.exe --i Novigrad2.schematic --o NovigradTest1

Then with FileToVox.exe --i Novigrad2.schematic --o NoviGradTest2 --sc 2

look into it both it seems that scale, scales every chunk, not the whole object

**Comment by Zarbuz** [comment]
![image](https://user-images.githubusercontent.com/4965714/107520562-d8771b80-6bb1-11eb-8e63-b3c60ef830c2.png)

It works perfectly well. You are confusing Minecraft chunks and MagicaVoxel chunks which are not the same thing at all. If you want bigger chunks in MagicaVoxel, you have to use the --chunk-size command (which is at the default value 125 and which can go up to 255 maximum)

![image](https://user-images.githubusercontent.com/4965714/107521248-9ac6c280-6bb2-11eb-84e7-5cb9db8fb4a5.png)
For example on the left here is what the conversion with this command gives: ./FileToVox.exe --i Novigrad2.schematic --o Novigrad --sc 2 --cs 255
