### ISSUE TITLE
Are you interested in converting Vox to Schematic？

### ISSUE THREAD

**Issue by akarinini** [Zarbuz/FileToVox#29]

**Comment by akarinini** [comment]
Hi, I am just a mc player and usually use MagicaVoxel. But i can not find such a program that can convert Vox to Schematic after mc1.13(issue#5) .
Would you consider writing such a program?

**Comment by Zarbuz** [comment]
Sorry I do not intend to write this kind of program.

**Comment by hellocatfood** [comment]
@akarinini you could try out these two scripts:

https://github.com/Kristopher38/vox2schematic
https://github.com/Voxelers/mcthings/tree/develop/bin

I'm not the developer of those plugins so if you have issues please contact them
