### ISSUE TITLE
.ply reader

### ISSUE THREAD

**Issue by petrasvestartas** [Zarbuz/FileToVox#3]
Hi,

I would like to use your software in a c# project as a library without cmd.exe

Could you show how to import .ply file format and get an array of mesh vertices and faces?

This is the file I am trying to import in c#:
[Poisson.zip](https://github.com/Zarbuz/FileToVox/files/3857982/Poisson.zip)

**Comment by petrasvestartas** [comment]
I found part of the code for the ply reader. But I see that the mesh faces are not implemented?

**Comment by Zarbuz** [comment]
Yes, my usage is mainly for cloud point at the moment
