### ISSUE TITLE
Missing required option: --i

### ISSUE THREAD

**Issue by Nacandcheese** [Zarbuz/FileToVox#32]
I was trying to convert a .tiff file using the converter, but the moment I ran the .exe it denied the conversion, stating that it was "Missing required option: --i". I tried to type FileToVox --help and it immediately shut down the command prompt window. Is there any way to fix this?
![image](https://user-images.githubusercontent.com/56834638/111393857-9006be00-8687-11eb-9da1-a775863f3c92.png)

**Comment by Zarbuz** [comment]
It's a console program. Not a classic executable. Please read the README for basic usage.
