### ISSUE TITLE
Converting a FBX / OBJ, resulting VOX file is too small to use.

### ISSUE THREAD

**Issue by visusys** [Zarbuz/FileToVox#39]
I am trying my best to figure out how to fix this. I downloaded the latest release of FileToVox and the GUI. Copied everything to the required paths:

FileToVoxGUI-v0.2
FileToVoxGUI-v0.2\FileToVox
FileToVoxGUI-v0.2\FileToVox\MeshSampler

Here are my settings:
![FileToVoxGUI](https://user-images.githubusercontent.com/33441569/136380607-53b30e3d-c825-440a-849e-ebb2b5aaeb1e.png)

Here is MeshSampler doing its thing:

![MeshSampler](https://user-images.githubusercontent.com/33441569/136380762-6cead276-babc-4348-acda-5a4f23795f85.png)

And here is the output file:
[test.zip](https://github.com/Zarbuz/FileToVox/files/7303074/test.zip)

Screenshot:
![MagicaVoxel_ZIfhiV5Ir0](https://user-images.githubusercontent.com/33441569/136380955-6c1e827b-7a23-40af-8fa9-9395551e7175.png)

As you can see in the screenshot, the result is just a tiny little spot on the 256x256 grid. 

Here is my input obj file, zipped: 
[input.zip](https://github.com/Zarbuz/FileToVox/files/7303088/input.zip)

How can I get this working properly? Would really, really appreciate any help!

J

**Comment by Zarbuz** [comment]
MeshSampler is having a massive rework. Should be fixed in FileToVox v1.14 with the release of MeshSampler v2

**Comment by visusys** [comment]
Sounds promising. Right now I've switched to obj2Voxel for the time being. It does what I need pretty well.

**Comment by Zarbuz** [comment]
MeshSampler v2 is released and bring better voxelization for 3D models, you can download it in the release section.
