### ISSUE TITLE
New files objects are z-offset to 256

### ISSUE THREAD

**Issue by rvorias** [Zarbuz/FileToVox#42]
Hi, thanks for the tool.

Whenever I apply a shader, my objects are transformed to z=256.
It would be cool if they stayed at their original position. If I use the fill tool, chances are I run out of memory.

Example:
```
FileToVox-v1.13-linux/FileToVox \
    --i MagicaVoxel-0.99.6.4-win64/vox/map_1.vox \
    --o MagicaVoxel-0.99.6.4-win64/vox/wmap_1 \
    --s shaders/flood.json
```

**Comment by Zarbuz** [comment]
Will be fixed in v1.14
