### ISSUE TITLE
Turn off color quantization

### ISSUE THREAD

**Issue by rvorias** [Zarbuz/FileToVox#43]
Hi,

I'm importing a bunch of png that represent slices of a .vox model.
All the pngs combined have a specific set of e.g. 20 colors.
However, the colors are getting quantized and some colors are getting squashed.

Is there an option to turn off color quantization?

**Comment by Zarbuz** [comment]
You can force to use the same palette that the existing palette in your different .vox

**Comment by rvorias** [comment]
I tried adding a palette with --palette and also some stuff with --cm but it didn't work.
Right now I just changed this:
https://github.com/Zarbuz/FileToVox/blob/c4a622151dc7152bc01c0da998a51816e6e9fbe7/SchematicToVoxCore/Quantizer/QuantizerBase.cs#L29
To:
```C#
return image;
```
And it works.
