### ISSUE TITLE
.xyz file results in smaller voxelized model

### ISSUE THREAD

**Issue by zenos4mbu** [Zarbuz/FileToVox#44]
Hello,

I'm trying to convert a simple 3D model from a .xyz file to a .vox to be visualized with MagicaVoxel, however the starting model has 1380 voxels but the converted one 348. 
[palm_island.txt](https://github.com/Zarbuz/FileToVox/files/7736113/palm_island.txt)

This is the terminal window, am I doing something wrong?

<img width="675" alt="palmisland_problem" src="https://user-images.githubusercontent.com/65705788/146568752-7534091f-42eb-462e-b791-48e42de93d30.png">
.

**Comment by Zarbuz** [comment]
Add the argument `--gs 1348`

**Comment by zenos4mbu** [comment]
Thanks :)
