### ISSUE TITLE
Grid scale cap

### ISSUE THREAD

**Issue by stringie** [Zarbuz/FileToVox#45]
You have written an amazing tool, but the current grid scale cap is between 128 and 2000.

Please increase the upper limit. I need it for a project.
Make it unlimited or just much higher.

**Comment by Zarbuz** [comment]
Maximal world edition in MagicaVoxel is 2000x2000x1000  (x z y). I can't write voxel which have coordinate beyond 2000 in any axis

**Comment by stringie** [comment]
oh wow, I did not know that. Thank you for responding :)
