### ISSUE TITLE
Feature request: Multiple pngs as input

### ISSUE THREAD

**Issue by vortextemporum** [Zarbuz/FileToVox#54]
Hi, first of all thanks for this awesome software!
I do algorithmic art so I automatize and experiment with things. For my needs, I would love to enter multiple png files in prompt and convert them into a vox file, rather than pointing to a folder (I have to move random/remove images in folders every time right now).

something like: --i path/to/file.png path/to/file2.png path/to/file3.png --o outfile.vox

Thanks!

p.s. also if this color optimization method at [https://github.com/Zarbuz/FileToVox/issues/43#issuecomment-987655860](https://github.com/Zarbuz/FileToVox/issues/43#issuecomment-987655860)  would be a command flag like --optimization=false, would be awesome!

**Comment by Zarbuz** [comment]
I'm not sure: in the end, each image would have the same position ? 
I can indeed add an option to turn off quantization however if the number of different colors in the image exceeds 255, it will only take the first 255

**Comment by vortextemporum** [comment]
> I'm not sure: in the end, each image would have the same position ?

I mean, each image will be rendered in a different height, image1 will be at bottom, image2 will be on top of it, image3 ....... just like how it reads and interprets the images in the folder.

**Comment by Zarbuz** [comment]
Ok ! I schedule this feature for 1.15!

**Comment by Zarbuz** [comment]
So the input would be like this : --i file1.png;file2.png;file3.png etc .. each file is separated by a semi-colon with no space
