### ISSUE TITLE
Problem converting files with MeshSampler 

### ISSUE THREAD

**Issue by ehsanps4** [Zarbuz/FileToVox#58]
Hello. Thank you so much for this great software.
There is a problem converting the file with MeshSampler.
blender
gpu: 1060
[file.zip](https://github.com/Zarbuz/FileToVox/files/8020066/file.zip)

**Comment by ehsanps4** [comment]
Hi. The file is not fully converted 
![1](https://user-images.githubusercontent.com/85092258/153490276-66e2ddb8-ead8-4392-9747-2d3250f5635b.jpg)
![2](https://user-images.githubusercontent.com/85092258/153490311-7ed0374f-5740-4ebd-9f04-8e2568ec2a0c.jpg)

**Comment by X-DE1** [comment]
I have problems tranforming this model https://www.models-resource.com/pc_computer/doomii/model/42383/
btw great tool and been looking for a tool like this for a long time
![SharedScreenshot](https://user-images.githubusercontent.com/101435795/157993797-c6dc9265-5164-4f68-8473-c1db25648e47.jpg)
![SharedScreenshot2](https://user-images.githubusercontent.com/101435795/157993818-8a7e7728-c564-44df-bcd2-22f68a0938c4.jpg)

**Comment by Zarbuz** [comment]
Fixed in the next version !

**Comment by ehsanps4** [comment]
Hello. This problem has not been resolved yet.
