### ISSUE TITLE
--cm work for obj?

### ISSUE THREAD

**Issue by superfrantv** [Zarbuz/FileToVox#6]
Greetings,

is it possible to generate a colored vox file from a obj and a png/mtl file or something other??

thanks for this great project :)

**Comment by Zarbuz** [comment]
No you can't have colored obj. But I would suggest you to convert your OBJ file into a PLY with CloudCompare and then convert it to FileToVox. I made a tutorial about this process : https://www.youtube.com/watch?v=sg3z2GaMJzM

**Comment by superfrantv** [comment]
Ok and if i import a ply File i can use --cm to add a texture map?
it's possible to import animated 3d model, so every frame it creates a vox file?

**Comment by Zarbuz** [comment]
Watch the video ;) PLY is a point cloud data. No texture but each points have a color. 
And no you can't import animated 3d model.

**Comment by superfrantv** [comment]
i love it, thats what i needed, thank you so much!!

**Comment by superfrantv** [comment]
I have some trouble with it, first how can i scale the Chunks in FileToVox? if i set --s 80 it doesnt change anything. Next is in CloudCompare my Colors are sometimes not imported right, whats the best file format to import in cloudcompare and export as ply? is this possible using a batch ?

**Comment by superfrantv** [comment]
And another Question, filetovox generates some empty chunks in magicavoxel, how can i change this?

**Comment by Zarbuz** [comment]
> I have some trouble with it, first how can i scale the Chunks in FileToVox? if i set --s 80 it doesnt change anything. Next is in CloudCompare my Colors are sometimes not imported right, whats the best file format to import in cloudcompare and export as ply? is this possible using a batch ?

The scale depend on the size of your models. I don't know how bug is the volume in voxels when you set a size of 80.

I import always in OBJ or sometimes in FBX, I haven't got any problem with colors and this is not a support of CloudCompare. Ask them in their forums.



> And another Question, filetovox generates some empty chunks in magicavoxel, how can i change this?

You have to manually delete it, there is no way to change it.
