### ISSUE TITLE
schematics/config.txt - what should be in it?

### ISSUE THREAD

**Issue by bokonon-bokonon** [Zarbuz/FileToVox#62]
Hi there
Sorry for using issues to ask for help. I really want to use this tool!

I'm trying to convert a .schematic to .vox, but it seems that a schematics/config.txt is required.

Can someone please help me - what should the config look like?

I'm using this schematic: https://www.planetminecraft.com/project/the-avengers---shield-helicarrier/

I'm running FileToVox it inside a linux docker container with dotnet installed.

Thank you!

Command:
` dotnet FileToVox-linux-x64/FileToVox.dll -i bind/helicarrier.schematic  -o bind/helicarrier.vox`

Console error:
<img width="943" alt="Screen Shot 2022-04-28 at 1 07 13 AM" src="https://user-images.githubusercontent.com/103638195/165528375-a459dd6d-61be-42f6-a07f-bc162cdd59ab.png">

Dockerfile:
```
ARG REPO=mcr.microsoft.com/dotnet/runtime-deps

# Installer image
FROM amd64/buildpack-deps:jammy-curl AS installer

# Retrieve .NET Runtime
RUN dotnet_version=6.0.4 \
    && curl -fSL --output dotnet.tar.gz https://dotnetcli.azureedge.net/dotnet/Runtime/$dotnet_version/dotnet-runtime-$dotnet_version-linux-x64.tar.gz \
    && dotnet_sha512='001487bfb337d0f737c4e3dedc4bc41b3185922c07c07e8f1d47e4578914fdeeed7421d7af2c4bb5e17ebddd05fde4cb9aea1e8145018dcffeaca70c1fa49bbb' \
    && echo "$dotnet_sha512  dotnet.tar.gz" | sha512sum -c - \
    && mkdir -p /dotnet \
    && tar -oxzf dotnet.tar.gz -C /dotnet \
    && rm dotnet.tar.gz


# .NET runtime image
FROM $REPO:6.0.4-jammy-amd64

# .NET Runtime version
ENV DOTNET_VERSION=6.0.4

COPY --from=installer ["/dotnet", "/usr/share/dotnet"]

RUN ln -s /usr/share/dotnet/dotnet /usr/bin/dotnet

# my stuff
COPY FileToVox-linux-x64 ./FileToVox-linux-x64
COPY bind ./bind
```

**Comment by Zarbuz** [comment]
[config.txt](https://github.com/Zarbuz/FileToVox/files/8582437/config.txt)
This is the config.txt I don't know why it wasn't included in the FileToVox build

**Comment by bokonon-bokonon** [comment]
Thank you, managed to get it working with that file.
