### ISSUE TITLE
Problem displaying material in MeshToVox

### ISSUE THREAD

**Issue by ehsanps4** [Zarbuz/FileToVox#63]
Hello. Thank you so much for this great software.
blender 2.93.6

file:

[test-2.zip](https://github.com/Zarbuz/FileToVox/files/8646815/test-2.zip)

[test-1.zip](https://github.com/Zarbuz/FileToVox/files/8646819/test-1.zip)

![test-2-obj-1](https://user-images.githubusercontent.com/85092258/167291670-b5789cd7-0705-4b6e-9e85-ae229d70f964.jpg)
obj

![test-2-obj-2](https://user-images.githubusercontent.com/85092258/167291687-c3248c18-4d05-4b02-87e5-18055d0473a8.jpg)
obj

--

![test-2-gltf-1](https://user-images.githubusercontent.com/85092258/167291717-a7fa1652-bd24-469a-9426-14c51ed6eb6d.jpg)
gltf

![test-2-gltf-2](https://user-images.githubusercontent.com/85092258/167291730-b2330b04-2051-4e20-9469-bf01a9c98c30.jpg)
gltf

--

![test-1-obj-1](https://user-images.githubusercontent.com/85092258/167291745-fccee1a2-dfd7-4b7d-bfc5-545e95db0b72.jpg)
obj

![test-1-obj-2](https://user-images.githubusercontent.com/85092258/167291750-62deb24f-05b4-41ac-a4b9-1b04c0598f37.jpg)
obj

**Comment by Zarbuz** [comment]
Fixed in MeshToVox v2.6
