### ISSUE TITLE
Empty Model

### ISSUE THREAD

**Issue by X-DE1** [Zarbuz/FileToVox#66]
I transformed this model with MeshToVox but when I opened it in voxelshop and magicavoxel nothing appeared.
https://www.models-resource.com/pc_computer/darksouls/model/51898/
I had a similar problem with this other model, the legs are not.
https://www.models-resource.com/pc_computer/darksouls/model/51900/

**Comment by Zarbuz** [comment]
Fixed in MeshToVox v2.7
