### ISSUE TITLE
Delete empty Chunks

### ISSUE THREAD

**Issue by superfrantv** [Zarbuz/FileToVox#7]
Hello,

i know iam ask this some time ago, but i very need a function to clear empty chunks out of the .vox file, do you know how to do this? I wish this will be possible.

you FileToVox Program ist so great, it should be more populare!

greetings from germany.

**Comment by Zarbuz** [comment]
Currently FileToVox is not able to skip empty chunks, you have to manually delete it in MagicaVoxel.

**Comment by Zarbuz** [comment]
I found motivation and I coded the requested feature. In the next version of FileToVox, empty chunks will be deleted !

**Comment by superfrantv** [comment]
Wow thats great to hear!

I think its also a way to extract each chunk to seperate vox Files. usefull for create landscapes and Export them to unity or something else.

**Comment by Zarbuz** [comment]
You can already do this in Magicavoxel : go to export -> "vox"
