### ISSUE TITLE
The required library hostfxr.dll could not be found

### ISSUE THREAD

**Issue by Anthys** [Zarbuz/FileToVox#8]
Hi, I'm on Windows 10. When I run FileToVox version 1.8.2, I get this error: 
`A fatal error occurred. The required library hostfxr.dll could not be found.
If this is a self-contained application, that library should exist in [C:\Logiciels\FileToVox-v1.8.2.win-x64\].     
If this is a framework-dependent application, install the runtime in the global location [C:\Program Files\dotnet] or use the DOTNET_ROOT environment variable to specify the runtime location or register the runtime location in [HKLM\SOFTWARE\dotnet\Setup\InstalledVersions\x64\InstallLocation].`.
However, when I use the version 1.8.0 or FileToVox, it works fine.

**Comment by superfrantv** [comment]
Hello same problem for me, how can we solve this? Need to install any microsoft library?

**Comment by Zarbuz** [comment]
Hello,
Sorry for this bug, can retry after installing this : https://dotnet.microsoft.com/download/dotnet-core/current/runtime ? 

If this solution helps, I will update the README.

**Comment by superfrantv** [comment]
Thanks worked fine :)
Some other Question its possible to implement a command: (delete all blocks who's has no side connected to other blocks) like the --e command?

**Comment by Zarbuz** [comment]
I will close this issue. Please open a new ticket for this request.
