### ISSUE TITLE
Bug Report on how the heightmap is generated

### ISSUE THREAD

**Issue by qnos** [Zarbuz/FileToVox#9]
When you convert a heightmap that is close to the size limit of MV the outmost row of voxboxes tends to overlap with the ones next to it because the edge pieces (that are smaller than 126³ voxels at this point) are still generated as a 126³ box of voxels. That overlap requires some fixing up in MV to make the heightmap useful.

Here's an example of how that looks: https://imgur.com/a/lZpm8pU

**Comment by Zarbuz** [comment]
Fixed. Available in the next version.
